extends Resource
class_name Constants

const MAX_CLIENTS = 2
const BASE_CARD_WIDTH = 240
const BASE_CARD_HEIGHT = 360
const ENTITY_SLOT_WIDTH = 160
const ENTITY_SCALE = ENTITY_SLOT_WIDTH / float(BASE_CARD_WIDTH)
const MIN_ATTACHMENT_Z_INDEX = -32